[build]
builder = "NIXPACKS"
installCommand = "npm install"
buildCommand = "npm run server:build"

[deploy]
startCommand = "rm -f dist/_expo/static/js/web/entry-f0d81efe56c6a797345dce3e0af6b1c3.js && PORT=8080 npm run server:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internalPort = 8080

[checks.web]
type = "http"
interval = 30000
timeout = 5000
method = "GET"
path = "/_health"
