import React from "react";
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity, Platform,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import Colors from "@/constants/colors";
import { BRAND } from "@/constants/brand";

const EFFECTIVE_DATE = "March 1, 2026";
const LAST_UPDATED = "March 8, 2026";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: `By creating an account or using TopRanker ("the App"), you agree to these Terms of Service ("Terms"). If you do not agree, do not use the App. These Terms constitute a legally binding agreement between you and TopRanker Inc. ("we," "us," "our").`,
  },
  {
    title: "2. Eligibility",
    body: `You must be at least 13 years old to use TopRanker. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf. We reserve the right to verify age and terminate accounts that do not meet eligibility requirements.`,
  },
  {
    title: "3. Trust Score & Credibility System",
    body: `TopRanker uses a proprietary trust-weighted ranking system ("Trust Score"). Your credibility tier (Community, City, Trusted, Top Ranker) is calculated algorithmically based on your activity, rating consistency, account age, and community engagement.

Trust Scores are:
- Algorithmic opinions generated by our system, not statements of fact
- Subject to change as our algorithms evolve
- Not a measure of personal trustworthiness outside the App
- Protected expression under Section 230 of the Communications Decency Act (US)

You acknowledge that Trust Scores may affect the weight of your ratings and that we may adjust the algorithm at any time without notice.`,
  },
  {
    title: "4. User Content & Ratings",
    body: `When you submit a rating, review, or photo ("User Content"), you:
- Grant TopRanker a worldwide, non-exclusive, royalty-free license to use, display, and distribute your User Content
- Represent that your Content is truthful and based on genuine experience
- Agree not to submit fake, misleading, or paid-for ratings
- Retain ownership of your User Content
- Ratings are processed in real-time and reflected in rankings immediately through our live update system

We reserve the right to remove any Content that violates these Terms, including but not limited to: spam, hate speech, defamation, or content designed to manipulate rankings.`,
  },
  {
    title: "5. Business Owner Rights",
    body: `Business owners who claim their listing may:
- Respond to ratings publicly
- Access analytics through the Business Dashboard
- Report inaccurate information for review

Business owners may NOT:
- Incentivize or coerce users to submit or remove ratings
- Create fake accounts to manipulate their ranking
- Use the Dashboard to identify or retaliate against individual raters

Violations may result in listing suspension or permanent removal.`,
  },
  {
    title: "6. Challenger Competitions",
    body: `The Challenger feature allows businesses to compete in 30-day head-to-head matchups. Entry fees ($99 per challenge) are non-refundable once a challenge begins. Results are determined solely by trust-weighted community votes. TopRanker does not guarantee any business outcome from Challenger participation.`,
  },
  {
    title: "7. Payments & Subscriptions",
    body: `Certain features require payment:
- Challenger Entry: $99 per challenge (one-time)
- Dashboard Pro: $49/month (recurring, cancel anytime)
- Featured Placement: $199/week (recurring)

All payments are processed through our payment provider (Stripe). Refund policies are governed by our Refund Policy. Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date.

You may cancel Featured Placement subscriptions at any time. Upon cancellation, your placement expires immediately and no further charges will be made. Challenger entries are non-refundable once a challenge begins.

Payment events are processed through secure webhook infrastructure. Failed payment events may be replayed by our operations team to ensure accurate account status.`,
  },
  {
    title: "8. Prohibited Conduct",
    body: `You agree not to:
- Create multiple accounts to manipulate rankings
- Use automated tools, bots, or scrapers
- Harass, threaten, or intimidate other users or business owners
- Reverse-engineer the Trust Score algorithm
- Sell or transfer your account or credibility tier
- Circumvent rate-gating or other anti-fraud measures
- Use the App for any unlawful purpose`,
  },
  {
    title: "9. Termination",
    body: `We may suspend or terminate your account at any time for violations of these Terms. Upon termination, your ratings may be retained in anonymized form for ranking integrity. You may delete your account through the App, which will remove your personal information in accordance with our Privacy Policy.`,
  },
  {
    title: "10. Disclaimers & Limitation of Liability",
    body: `THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THE ACCURACY OF RANKINGS, TRUST SCORES, OR USER CONTENT. IN NO EVENT SHALL TOPRANKER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APP.

Our maximum aggregate liability for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: "11. Governing Law",
    body: `These Terms are governed by the laws of the State of Texas, United States, without regard to conflict of law principles. For users in India, applicable provisions of the Information Technology Act 2000, Consumer Protection Act 2019, and Digital Personal Data Protection Act 2023 shall apply to the extent required by law.`,
  },
  {
    title: "12. Changes to Terms",
    body: `We may update these Terms at any time. Material changes will be communicated via in-app notification or email at least 30 days before taking effect. Continued use after changes constitutes acceptance.`,
  },
  {
    title: "13. Real-Time Data & Communications",
    body: `TopRanker delivers real-time updates through server-sent events (SSE) when you use the App. This includes live ranking changes, rating updates, and challenge results.

Transactional emails (welcome, payment confirmations, challenge results) are sent via our email provider. You may not opt out of transactional emails while maintaining an active account. Marketing and promotional communications can be managed in your notification settings.

We reserve the right to send service-critical notifications (security alerts, terms changes, payment issues) regardless of notification preferences.`,
  },
  {
    title: "14. Contact",
    body: `For legal inquiries: legal@topranker.com
For support: support@topranker.com
TopRanker Inc., Dallas, TX, United States`,
  },
];

export default function TermsOfService() {
  const insets = useSafeAreaInsets();
  const topPad = Platform.OS === "web" ? 20 : insets.top;

  return (
    <View style={[styles.container, { paddingTop: topPad }]}>
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => router.back()}
          style={styles.backBtn}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Ionicons name="chevron-back" size={22} color={Colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 32 }} />
      </View>

      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.effectiveDate}>
          Effective: {EFFECTIVE_DATE} | Last Updated: {LAST_UPDATED}
        </Text>

        {SECTIONS.map((section, i) => (
          <View key={i} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionBody}>{section.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backBtn: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: Colors.text,
    fontFamily: "PlayfairDisplay_700Bold",
  },
  content: { paddingHorizontal: 20, paddingTop: 16 },
  effectiveDate: {
    fontSize: 12,
    color: Colors.textTertiary,
    fontFamily: "DMSans_400Regular",
    marginBottom: 20,
    textAlign: "center",
  },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text,
    fontFamily: "DMSans_700Bold",
    marginBottom: 8,
  },
  sectionBody: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontFamily: "DMSans_400Regular",
    lineHeight: 22,
  },
});
