/**
 * Mock data for offline/demo mode.
 * Used when the backend API is unreachable (no DATABASE_URL).
 * Provides realistic Dallas restaurant data for visual testing.
 */

import type { ApiBusiness, ApiRating, ApiChallenger, ApiMemberProfile, ApiMemberImpact } from "./api";

const now = new Date().toISOString();
const dayAgo = new Date(Date.now() - 86400000).toISOString();
const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString();

export const MOCK_BUSINESSES: ApiBusiness[] = [
  {
    id: "mock-1",
    name: "Pecan Lodge",
    slug: "pecan-lodge",
    category: "restaurants",
    cuisine: "american",
    city: "Dallas",
    neighborhood: "Deep Ellum",
    address: "2702 Main St, Dallas, TX 75226",
    lat: "32.7837",
    lng: "-96.7836",
    phone: "(214) 748-8900",
    website: "https://pecanlodge.com",
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "9.42",
    rawAvgScore: "9.10",
    rankPosition: 1,
    rankDelta: 0,
    prevRankPosition: 1,
    totalRatings: 487,
    isActive: true,
    inChallenger: false,
    description: "Award-winning BBQ in the heart of Deep Ellum. Known for brisket, ribs, and banana pudding.",
    priceRange: "$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.6",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Mon-Sat: 11AM-8PM", "Sun: 11AM-4PM"] },
  },
  {
    id: "mock-2",
    name: "Lucia",
    slug: "lucia",
    category: "restaurants",
    cuisine: "italian",
    city: "Dallas",
    neighborhood: "Bishop Arts",
    address: "408 W 8th St, Dallas, TX 75208",
    lat: "32.7468",
    lng: "-96.8268",
    phone: "(214) 948-4998",
    website: "https://luciadallas.com",
    photoUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400",
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400",
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400",
    ],
    weightedScore: "9.31",
    rawAvgScore: "9.05",
    rankPosition: 2,
    rankDelta: 1,
    prevRankPosition: 3,
    totalRatings: 312,
    isActive: true,
    inChallenger: true,
    description: "Italian-inspired neighborhood restaurant with handmade pasta and seasonal menus.",
    priceRange: "$$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.7",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Tue-Sat: 5:30PM-10PM", "Sun-Mon: Closed"] },
  },
  {
    id: "mock-3",
    name: "Uchi Dallas",
    slug: "uchi-dallas",
    category: "restaurants",
    cuisine: "japanese",
    city: "Dallas",
    neighborhood: "Oak Lawn",
    address: "2817 Maple Ave, Dallas, TX 75201",
    lat: "32.8023",
    lng: "-96.8100",
    phone: "(214) 855-5454",
    website: "https://uchidallas.com",
    photoUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400",
      "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=400",
    ],
    weightedScore: "9.18",
    rawAvgScore: "8.95",
    rankPosition: 3,
    rankDelta: -1,
    prevRankPosition: 2,
    totalRatings: 278,
    isActive: true,
    inChallenger: true,
    description: "Japanese farmhouse dining with innovative sushi and hot tastings.",
    priceRange: "$$$$",
    isOpenNow: false,
    isClaimed: true,
    googleRating: "4.5",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Sun-Thu: 5PM-10PM", "Fri-Sat: 5PM-11PM"] },
  },
  {
    id: "mock-4",
    name: "Terry Black's BBQ",
    slug: "terry-blacks-bbq",
    category: "restaurants",
    cuisine: "american",
    city: "Dallas",
    neighborhood: "Deep Ellum",
    address: "3025 Main St, Dallas, TX 75226",
    lat: "32.7840",
    lng: "-96.7790",
    phone: "(469) 399-0081",
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400",
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=400",
      "https://images.unsplash.com/photo-1558030006-450675393462?w=400",
    ],
    weightedScore: "9.05",
    rawAvgScore: "8.80",
    rankPosition: 4,
    rankDelta: 2,
    prevRankPosition: 6,
    totalRatings: 356,
    isActive: true,
    inChallenger: false,
    description: "Central Texas-style BBQ. Pit-smoked meats, classic sides, craft cocktails.",
    priceRange: "$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.5",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Daily: 11AM-9PM"] },
  },
  {
    id: "mock-5",
    name: "Homewood",
    slug: "homewood",
    category: "restaurants",
    cuisine: "american",
    city: "Dallas",
    neighborhood: "Oak Cliff",
    address: "4100 Maple Ave, Dallas, TX 75219",
    lat: "32.8052",
    lng: "-96.8170",
    phone: "(214) 741-4663",
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.94",
    rawAvgScore: "8.70",
    rankPosition: 5,
    rankDelta: 0,
    prevRankPosition: 5,
    totalRatings: 201,
    isActive: true,
    inChallenger: false,
    description: "Wood-fired cooking with hyper-seasonal menus. Intimate neighborhood spot.",
    priceRange: "$$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.6",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Wed-Sun: 5PM-10PM", "Mon-Tue: Closed"] },
  },
  {
    id: "mock-6",
    name: "Cattleack Barbeque",
    slug: "cattleack-barbeque",
    category: "restaurants",
    cuisine: "american",
    city: "Dallas",
    neighborhood: "Farmers Branch",
    address: "13628 Gamma Rd, Dallas, TX 75244",
    lat: "32.9312",
    lng: "-96.8591",
    phone: null,
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.87",
    rawAvgScore: "8.60",
    rankPosition: 6,
    rankDelta: -2,
    prevRankPosition: 4,
    totalRatings: 198,
    isActive: true,
    inChallenger: false,
    description: "Limited-hours BBQ joint famous for brisket and ribs. Thu-Sat only.",
    priceRange: "$$",
    isOpenNow: false,
    isClaimed: false,
    googleRating: "4.8",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Thu-Sat: 10:30AM-2PM or sold out", "Sun-Wed: Closed"] },
  },
  {
    id: "mock-7",
    name: "Meridian",
    slug: "meridian",
    category: "restaurants",
    cuisine: "vietnamese",
    city: "Dallas",
    neighborhood: "Bishop Arts",
    address: "327 N Bishop Ave, Dallas, TX 75208",
    lat: "32.7506",
    lng: "-96.8279",
    phone: "(469) 781-5858",
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.73",
    rawAvgScore: "8.50",
    rankPosition: 7,
    rankDelta: 1,
    prevRankPosition: 8,
    totalRatings: 165,
    isActive: true,
    inChallenger: false,
    description: "Modern American cuisine with Vietnamese influences. Creative cocktails.",
    priceRange: "$$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.4",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Tue-Sun: 5PM-10PM", "Mon: Closed"] },
  },
  {
    id: "mock-8",
    name: "Nori Handroll Bar",
    slug: "nori-handroll-bar",
    category: "restaurants",
    cuisine: "japanese",
    city: "Dallas",
    neighborhood: "Highland Park",
    address: "4334 Lovers Ln, Dallas, TX 75225",
    lat: "32.8399",
    lng: "-96.7982",
    phone: null,
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.61",
    rawAvgScore: "8.40",
    rankPosition: 8,
    rankDelta: 3,
    prevRankPosition: 11,
    totalRatings: 142,
    isActive: true,
    inChallenger: false,
    description: "Premium hand roll sushi bar. Omakase-style counter seating.",
    priceRange: "$$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.5",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Daily: 11:30AM-9:30PM"] },
  },
  {
    id: "mock-9",
    name: "Cane Rosso",
    slug: "cane-rosso",
    category: "restaurants",
    cuisine: "italian",
    city: "Dallas",
    neighborhood: "Deep Ellum",
    address: "2612 Commerce St, Dallas, TX 75226",
    lat: "32.7823",
    lng: "-96.7858",
    phone: "(214) 741-1188",
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.48",
    rawAvgScore: "8.25",
    rankPosition: 9,
    rankDelta: -1,
    prevRankPosition: 8,
    totalRatings: 234,
    isActive: true,
    inChallenger: false,
    description: "Neapolitan-style pizza with locally sourced ingredients.",
    priceRange: "$$",
    isOpenNow: true,
    isClaimed: true,
    googleRating: "4.3",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Mon-Thu: 11AM-10PM", "Fri-Sat: 11AM-11PM", "Sun: 11AM-9PM"] },
  },
  {
    id: "mock-10",
    name: "Tei-An",
    slug: "tei-an",
    category: "restaurants",
    cuisine: "japanese",
    city: "Dallas",
    neighborhood: "Arts District",
    address: "1722 Routh St, Dallas, TX 75201",
    lat: "32.7890",
    lng: "-96.7990",
    phone: "(214) 220-2828",
    website: null,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    photoUrls: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    ],
    weightedScore: "8.35",
    rawAvgScore: "8.10",
    rankPosition: 10,
    rankDelta: 0,
    prevRankPosition: 10,
    totalRatings: 189,
    isActive: true,
    inChallenger: false,
    description: "Hand-cut soba noodles and Japanese small plates in the Dallas Arts District.",
    priceRange: "$$$",
    isOpenNow: false,
    isClaimed: true,
    googleRating: "4.4",
    googleMapsUrl: null,
    openingHours: { weekday_text: ["Tue-Sat: 11AM-2PM, 5PM-10PM", "Sun-Mon: Closed"] },
  },
];

export const MOCK_RATINGS: ApiRating[] = [
  {
    id: "rating-1",
    memberId: "member-1",
    businessId: "mock-1",
    q1Score: 10,
    q2Score: 9,
    q3Score: 9,
    wouldReturn: true,
    note: "Best brisket I've ever had. The bark is perfect and the meat melts in your mouth. Banana pudding is a must.",
    rawScore: "9.33",
    weight: "1.00",
    weightedScore: "9.33",
    isFlagged: false,
    autoFlagged: false,
    source: "app",
    createdAt: dayAgo,
    memberName: "Sarah Chen",
    memberTier: "top",
    memberAvatarUrl: null,
  },
  {
    id: "rating-2",
    memberId: "member-2",
    businessId: "mock-1",
    q1Score: 9,
    q2Score: 9,
    q3Score: 10,
    wouldReturn: true,
    note: "Consistently excellent. The beef rib is a showstopper. Long lines but worth every minute.",
    rawScore: "9.33",
    weight: "0.70",
    weightedScore: "6.53",
    isFlagged: false,
    autoFlagged: false,
    source: "app",
    createdAt: weekAgo,
    memberName: "Marcus Johnson",
    memberTier: "trusted",
    memberAvatarUrl: null,
  },
  {
    id: "rating-3",
    memberId: "member-3",
    businessId: "mock-1",
    q1Score: 8,
    q2Score: 9,
    q3Score: 8,
    wouldReturn: true,
    note: "Great BBQ, solid sides. A bit crowded but the food makes up for it.",
    rawScore: "8.33",
    weight: "0.35",
    weightedScore: "2.92",
    isFlagged: false,
    autoFlagged: false,
    source: "app",
    createdAt: weekAgo,
    memberName: "Alex Rivera",
    memberTier: "city",
    memberAvatarUrl: null,
  },
  {
    id: "rating-4",
    memberId: "member-4",
    businessId: "mock-1",
    q1Score: 10,
    q2Score: 10,
    q3Score: 9,
    wouldReturn: true,
    note: "Perfection. Simply the best BBQ in Texas.",
    rawScore: "9.67",
    weight: "0.10",
    weightedScore: "0.97",
    isFlagged: false,
    autoFlagged: false,
    source: "app",
    createdAt: now,
    memberName: "Kim Patel",
    memberTier: "community",
    memberAvatarUrl: null,
  },
];

export const MOCK_DISHES = [
  { id: "dish-1", businessId: "mock-1", name: "Brisket", nameNormalized: "brisket", voteCount: 342, isActive: true },
  { id: "dish-2", businessId: "mock-1", name: "Beef Rib", nameNormalized: "beef_rib", voteCount: 256, isActive: true },
  { id: "dish-3", businessId: "mock-1", name: "Banana Pudding", nameNormalized: "banana_pudding", voteCount: 198, isActive: true },
  { id: "dish-4", businessId: "mock-1", name: "Pulled Pork", nameNormalized: "pulled_pork", voteCount: 145, isActive: true },
];

export const MOCK_CHALLENGERS: ApiChallenger[] = [
  {
    id: "challenge-1",
    challengerId: "mock-2",
    defenderId: "mock-3",
    category: "restaurants",
    city: "Dallas",
    startDate: new Date(Date.now() - 15 * 86400000).toISOString(),
    endDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    challengerWeightedVotes: "156.4",
    defenderWeightedVotes: "142.8",
    totalVotes: 89,
    status: "active",
    challengerBusiness: MOCK_BUSINESSES[1],
    defenderBusiness: MOCK_BUSINESSES[2],
  },
  {
    id: "challenge-2",
    challengerId: "mock-8",
    defenderId: "mock-9",
    category: "restaurants",
    city: "Dallas",
    startDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    endDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    challengerWeightedVotes: "48.2",
    defenderWeightedVotes: "51.6",
    totalVotes: 34,
    status: "active",
    challengerBusiness: MOCK_BUSINESSES[7],
    defenderBusiness: MOCK_BUSINESSES[8],
  },
];

export const MOCK_MEMBER_PROFILE: ApiMemberProfile = {
  id: "demo-member",
  displayName: "Alex Demo",
  username: "alexdemo",
  email: "alex@demo.com",
  city: "Dallas",
  avatarUrl: null,
  credibilityScore: 72,
  credibilityTier: "trusted",
  totalRatings: 48,
  totalCategories: 5,
  distinctBusinesses: 32,
  isFoundingMember: true,
  joinedAt: "2024-06-15T00:00:00Z",
  daysActive: 267,
  ratingVariance: 1.8,
  credibilityBreakdown: {
    base: 10,
    volume: 18,
    diversity: 15,
    age: 12,
    variance: 8,
    helpfulness: 9,
    penalties: 0,
  },
  ratingHistory: [
    { ...MOCK_RATINGS[0], businessName: "Pecan Lodge" },
    { ...MOCK_RATINGS[1], businessName: "Pecan Lodge" },
  ],
  // Sprint 574: Dish vote streak tracking
  dishVoteStreak: 5,
  longestDishStreak: 12,
  totalDishVotes: 34,
  topDish: "Brisket",
};

export const MOCK_MEMBER_IMPACT: ApiMemberImpact = {
  businessesMovedUp: 7,
  topContributions: [
    { name: "Pecan Lodge", slug: "pecan-lodge", rankChange: 2 },
    { name: "Terry Black's BBQ", slug: "terry-blacks-bbq", rankChange: 3 },
    { name: "Nori Handroll Bar", slug: "nori-handroll-bar", rankChange: 4 },
  ],
};

export const MOCK_RANK_HISTORY = Array.from({ length: 30 }, (_, i) => {
  const date = new Date(Date.now() - (29 - i) * 86400000);
  const baseRank = 1;
  const wobble = Math.sin(i * 0.5) * 0.3;
  return {
    date: date.toISOString().split("T")[0],
    rank: Math.max(1, Math.round(baseRank + wobble)),
    score: 9.42 - wobble * 0.1,
  };
});

export const MOCK_CATEGORIES = ["restaurants", "fast_food", "cafes", "bars", "fine_dining", "bakeries"];
